version = 0.1
[default.deploy.parameters]
stack_name = "appsync-ddb-integration"
resolve_s3 = true
s3_prefix = "appsync-ddb-integration"
region = "eu-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "TableName=\"Table\" ApiName=\"ApiName\" ApiKeyExpiration=\"100000\""
image_repositories = []
